name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Pandoc build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get GH package
        run:
          wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb

      - name: Install Pandoc
        run:
          sudo dpkg -i pandoc-2.19.2-1-amd64.deb

      - name: Build
        run:
          make public/index.html

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses:
#       # - uses: actions/checkout@v2
#       # - uses: actions/setup-pandoc@v1
#       # - run: make public/index.html
#       # - uses: actions/deploy-to-github-pages@v1
#       #   with:
#       #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       #     BRANCH: gh-pages
#       #     FOLDER: .
